spring:
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Drvier
    url: jdbc:mysql://loaclhost:3306/smallblog?userUnicode=true&characterEncoding=utf-8
    username: root
    password: 1111

  #
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

# 日志配置
logging:
  level:
    root: warn
    com.lrm: info
  file: log/blog-pro.log

# 端口号
server:
  port: 8081

