# 配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/usermanager?characterEncoding=utf8
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

# 开启MyBatis SQL打印
logging:
  level:
    com:
      demo: debug

# mybatis 配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl